### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#484]
- [x] Add documentation about `$distro_old` logo variants.
- [x] **https://github.com/dylanaraps/neofetch/pull/502**: Look into detecting screenshot tools instead of the user having to manually specify the tool they have installed. 
- [x] Update wiki pages.
