### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#511]
- [ ] Revisit info caching and do it properly this time.
    - Check to see if flags were used or config options were changed before automatically using cached value.
- [x] Integrate `shellcheck` with travis.ci
    - [x] Make a list of `shellcheck` error codes we can exclude.
- [x] Look into optimizing `get_de()`, `get_wm()` and `get_term()` usage.
- [x] Remove some bloat.

**Comment by dylanaraps** [comment]
Doing info caching properly will be difficult since we also have to cache values of options and then check to see if those options were changed. We're only caching GPU on macOS now so I'm just going to simplify the caching as much as possible.

**Comment by ShalokShalom** [comment]
neofetch use for "Theme" and "Icon" the Theme and Icon from kde-gtk-config:

![sdxij](https://cloud.githubusercontent.com/assets/6344099/21417972/7247ae32-c81e-11e6-862f-a14c218e7f14.png)


![screenshot_20161222_081124](https://cloud.githubusercontent.com/assets/6344099/21417957/4499d87a-c81e-11e6-92a1-48e5eb7d66be.png)

Instead from here:

![screenshot_20161222_080820](https://cloud.githubusercontent.com/assets/6344099/21417877/d559402c-c81d-11e6-8b33-6ae8ea1fcddb.png)

![screenshot_20161222_080758](https://cloud.githubusercontent.com/assets/6344099/21417880/d9c46c18-c81d-11e6-863b-2adb54e72900.png)

Additional Info: The Look and Feel packages are meta packages for Theme, Cursor, Icons and so on.
You might want to add that info to your neofetch, when Plasma5 is detected.

**Comment by dylanaraps** [comment]
I'll look into it, thanks!

**Comment by dylanaraps** [comment]
@ShalokShalom, the issue should be fixed now. Try the latest master.

**Comment by carguello** [comment]
@dylanaraps Where is the latest commit, can't seem to find it

**Comment by dylanaraps** [comment]
Follow these instructions to install the latest unreleased snapshot:

https://github.com/dylanaraps/neofetch/wiki/Installation#latest-git-master-bleeding-edge

**Comment by carguello** [comment]
@dylanaraps Oh ok, the thing is that, I'm in the process of porting Neofetch to KaOS, I don't really know how to get the PKGBUILD out. I did before but with the AUR PKG

**Comment by dylanaraps** [comment]
KaOS uses `pacman` right? 

I'm packaging Neofetch for Arch Linux so I can help you out if you're having trouble.

**Comment by carguello** [comment]
Yes pacman, sure please

**Comment by dylanaraps** [comment]
The existing PKGBUILDs should work just fine on KaOS right?

Latest Release: 

- aur page: https://aur.archlinux.org/packages/neofetch/
- PKGBUILD: https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=neofetch

Latest Unreleased Version:

- aur page: https://aur.archlinux.org/packages/neofetch-git/
- PKGBUILD: https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=neofetch-git

All that should be needed is to use the existing PKGBUILDs.

**Comment by carguello** [comment]
Yeah, last time I worked with the **Latest Release** I'll go with the  **Unreleased**

**Comment by carguello** [comment]
Updated, thanks

![Updated](https://u.teknik.io/xDMwM.png)

**Comment by ShalokShalom** [comment]
@dylanaraps  Thanks a lot dude

KaOS use different names in same cases for its packages and it use mostly the split setup from upstream. If you are interested to build other KaOS packages, for some reason, here are some important notes:

https://kaosx.us/docs/package/#list-of-common-renames

**Comment by dylanaraps** [comment]
No problem!

None of those renames affect Neofetch. :)

**Comment by ShalokShalom** [comment]
They are just examples, thanks a lot again. :)
