### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#613]
If you'd like to work on one of these, let me know in IRC or gitter so I can assign it to you.

**General**

- [ ] Rewrite printing of info.
    - [ ] Add alignment options.
- [ ] Rewrite Neofetch to be a "generic system info tool"
    - Each format below will be a different output "mode".
    - [ ] Output info with no escape sequences. #617 
    - [ ] Output info in `yaml`. #617 
    - [ ] Output info in `json`. #617 
    - [ ] Output info in a `tab separated` format. #617 
    - [ ] Output info in ?
- [ ] Split Neofetch into multiple files.
    - This will likely be apart of the rewrite above.
- [ ] Rewrite argument handling.
    - [ ] Parse the argument list properly.
    - [ ] Remove complexity of `--colors` and etc.
    - [ ] Possibly inform users of incorrect flag usage.
        - [ ] Warn on invalid flag value.
        - [ ] Warn on flags that require values.
    - [ ] Add flag called `--print` which takes a list of functions.
        - Example: `neofetch --print cpu` will only print the cpu info.
    - [x] Hand relative file paths correctly. #623 
        - [x] Rewrite `get_script_dir()` to be a generic replacement for `readlink -f`. #623 
- [ ] Rewrite color handling.
    - It's a mess right now.
    - [ ] Add back shortcut flags for colors.
        - [ ] `title_color`
        - [ ] `at_color`
        - [ ] `underline_color`
        - [ ] `subtitle_color`
        - [ ] `colon_color`
        - [ ] `info_color`
- [x] Fix inconsistencies in `neofetch --help` output.
    - [x] Change all `Takes the values` to `Possible values`.
- [x] Add `config_version` to config files so that we can do version checks in the future.
    - `config_version` can just match neofetch version.

**Images**

- [x] Move all image modes to a central backend. #616
    - This way the user specifies a single backend using a flag/option and neofetch just has to pick the output method. We already partly do this but I'd like to fully combine it all.
    - [x] Move ascii mode to an image backend called `ascii`. 
    - [x] Move off mode to an image backend called `off`. 
    - [x] Add support for `catimg`. 
    - [x] Add support for other backends. 

**OS**

- [ ] Add support for HP-UX. #625 

**Info**

- [ ] Resolution: Multi-monitor support for Windows.
    - Our current method of using `wmic` only supports single monitors.
    - We may need to add a dependency to an external powershell script or executable.
       - The dependency must be Open Source.
- [ ] Terminal Font: Add support for more terminal emulators.
    - [ ] `Gnome-terminal`
    - [ ] `iTerm2`
    - [ ] `Terminator`
    - [ ] ?
- [ ] Disk: 
    - [ ] Add an option to show all disks.
    - [ ] Add more subtitle options.
    - [ ] Add a blacklist/whitelist for disks.

**Wiki**

- [ ] Add a section to `Images in the Terminal` about disabling your compositor when you're having `w3m-img` issues.
- [x] Update dependencies for `3.0.1`.

**Comment by dylanaraps** [comment]
Neofetch 3.0 Checklist.

- [ ] Look over commit history.
    - [ ] Look for changes that are missing from the Changelog.
    - [ ] Look for any obvious bugs.
- [ ] Change all occurrences of `2.1.0` to `3.0`.
- [ ] Rewrite the Changelog.
    - [ ] Highlight new features.
    - [ ] Explain the version bump.
- [ ] Update the Wiki
    - [ ]  Add a section to Images in the Terminal about disabling your compositor when you're having `w3m-img` issues.
    - [ ] Add a Wiki page about the new image backends.

**Comment by dylanaraps** [comment]
> I'll keep this here and re-use it for every release.

**Release Checklist.**

Preparation:

- [x] Bump version numbers.
    - [x] Inside `neofetch`.
    - [x] Inside `config/config`.
    - [x] Inside `neofetch.1` (`--gen-man`).
- [ ] Update the Changelog
    - [x] Spelling / Grammar / Formatting
    - [x] Have all contributors been credited?
    - [x] Have all relevant changes been added?

Release:

- [ ] Update the Wiki.
    - [ ] Update download link in Installation Wiki page.
    - [ ] Update config file in config file Wiki page.
    - [ ] Update dependencies page if there are new dependencies.
    - [ ] Update OS support.
    - [ ] Update other pages if information has changed.
- [ ] Delete the changelog file and start new.
- [ ] Clear the package update issue thread.
